const CONTEXT_MAP = {
  CONSTANTS: 'CONSTANTS',
  CONFIG: 'CONFIG',
  API_KEY: 'API_KEY',
  CLIENT_ID: 'CLIENT_ID',
  SESSION_ID: 'SESSION_ID',
  PUBLIC_KEY: 'PUBLIC_KEY',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  APP_UID: 'APP_UID',
  REQUEST_ID: 'REQUEST_ID'
}

export default CONTEXT_MAP

export const ROTATE_VALUE_KEYS = [
  CONTEXT_MAP.ACCESS_TOKEN,
  CONTEXT_MAP.PUBLIC_KEY
]
